title: Cream and Crust

name: "Cream and Crust"
job: "Authentic mama's bakery"

phone_number: 07777777777
address: Jerusalem, Israel
email: cream.an.crust@gmail.com
github_username: Creamandcrust.github.io
blog_url: homepage-url

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
