title: dtyh dghj 

name: "Mj"
job: "〈MSc Student | WIS〉"

phone_number: 07777777777
address: Rehovot, Israel
email: 
linkedin_username: ftgyj
github_username: dgthdj
instagram_username: dghdj
twitter_username: jdfghj
facebook_username: dgj dfgjyj
youtube_username: youtube
blog_url: homepage-url

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
